[package]
name = "digibyte"
version = "0.27.3"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>", "Gary Mckee <gary@lifehash.com>"]
license = "CC0-1.0"
homepage = "https://github.com/digicontributer/rust-digibyte/"
repository = "https://github.com/digicontributer/rust-digibyte/"
documentation = "https://docs.rs/bitcoin/"
description = "General purpose library for using and interoperating with DigiByte and other cryptocurrencies."
keywords = [ "crypto", "digibyte" ]
readme = "README.md"


[features]
default = [ "secp-recovery" ]
base64 = [ "base64-compat" ]
fuzztarget = ["bitcoin_hashes/fuzztarget"]
unstable = []
rand = ["secp256k1/rand-std"]
use-serde = ["serde", "bitcoin_hashes/serde", "secp256k1/serde"]
secp-lowmemory = ["secp256k1/lowmemory"]
secp-recovery = ["secp256k1/recovery"]

[dependencies]
bech32 = "0.7.2"
bitcoin_hashes = "0.9.1"
secp256k1 = "0.20.0"

base64-compat = { version = "1.0.0", optional = true }
bitcoinconsensus = { version = "0.19.0-1", optional = true }
serde = { version = "1", features = [ "derive" ], optional = true }

[dev-dependencies]
serde_json = "<1.0.45"
serde_test = "1"
secp256k1 = { version = "0.20.0", features = [ "recovery", "rand-std" ] }
bincode = "1.3.1"
# We need to pin ryu (transitive dep from serde_json) to stay compatible with Rust 1.22.0
ryu = "<1.0.5"
